CREATE SEQUENCE hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE img_sequence
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE flow_sequence
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
